-- Snowflake Raw Schema DDL — WBS 1.1.1
-- 실행 환경: Snowflake Worksheet 또는 snowflake_loader.py 초기화 시 자동 실행
-- 멱등성 보장: IF NOT EXISTS 사용 — 재실행 안전
-- 자연 키 컬럼은 MERGE INTO 업서트 기준으로 사용 (snowflake_loader.py 참조)

-- ── 데이터베이스 / 스키마 ────────────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS SOYBEAN_OIL;
CREATE SCHEMA IF NOT EXISTS SOYBEAN_OIL.RAW;

-- ── WBS 1.1.2: 경제 지표 ─────────────────────────────────────────────────────
-- 자연 키: (PRICE_DATE, SOURCE_NAME, INDICATOR_CODE)
CREATE TABLE IF NOT EXISTS SOYBEAN_OIL.RAW.ECONOMIC_INDICATORS (
    PRICE_DATE      DATE           NOT NULL,
    SOURCE_NAME     VARCHAR(100)   NOT NULL,
    INDICATOR_CODE  VARCHAR(100)   NOT NULL,
    VALUE           FLOAT          NOT NULL,
    UNIT            VARCHAR(50),
    INGESTED_AT     TIMESTAMP_NTZ  NOT NULL,
    _LOADED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ECON PRIMARY KEY (PRICE_DATE, SOURCE_NAME, INDICATOR_CODE)
);

-- ── WBS 1.1.3: 해운 지수 ─────────────────────────────────────────────────────
-- 자연 키: (PRICE_DATE, INDICATOR_CODE)
CREATE TABLE IF NOT EXISTS SOYBEAN_OIL.RAW.SHIPPING_INDICES (
    PRICE_DATE      DATE           NOT NULL,
    SOURCE_NAME     VARCHAR(100)   NOT NULL,
    INDICATOR_CODE  VARCHAR(50)    NOT NULL,
    VALUE           FLOAT          NOT NULL,
    UNIT            VARCHAR(50),
    NOTE            VARCHAR(200),
    INGESTED_AT     TIMESTAMP_NTZ  NOT NULL,
    _LOADED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SHIP PRIMARY KEY (PRICE_DATE, INDICATOR_CODE)
);

-- ── WBS 1.1.4: WASDE 작황 데이터 ─────────────────────────────────────────────
-- 자연 키: (PRICE_DATE, SOURCE_NAME, INDICATOR_CODE, COUNTRY)
CREATE TABLE IF NOT EXISTS SOYBEAN_OIL.RAW.CROP_DATA (
    PRICE_DATE      DATE           NOT NULL,
    SOURCE_NAME     VARCHAR(100)   NOT NULL,
    INDICATOR_CODE  VARCHAR(100)   NOT NULL,
    COUNTRY         VARCHAR(100)   NOT NULL DEFAULT '',
    VALUE           FLOAT          NOT NULL,
    UNIT            VARCHAR(50),
    INGESTED_AT     TIMESTAMP_NTZ  NOT NULL,
    _LOADED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CROP PRIMARY KEY (PRICE_DATE, SOURCE_NAME, INDICATOR_CODE, COUNTRY)
);

-- ── WBS 1.1.5: 기후 / ENSO ──────────────────────────────────────────────────
-- 자연 키: (PRICE_DATE, SOURCE_NAME, INDICATOR_CODE, SEASON)
CREATE TABLE IF NOT EXISTS SOYBEAN_OIL.RAW.CLIMATE_DATA (
    PRICE_DATE      DATE           NOT NULL,
    SOURCE_NAME     VARCHAR(100)   NOT NULL,
    INDICATOR_CODE  VARCHAR(100)   NOT NULL,
    SEASON          VARCHAR(10)    NOT NULL DEFAULT '',
    VALUE           FLOAT          NOT NULL,
    UNIT            VARCHAR(50),
    ENSO_PHASE      VARCHAR(20),
    INGESTED_AT     TIMESTAMP_NTZ  NOT NULL,
    _LOADED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CLIMATE PRIMARY KEY (PRICE_DATE, SOURCE_NAME, INDICATOR_CODE, SEASON)
);

-- ── WBS 1.1.6: 지정학 리스크 ────────────────────────────────────────────────
-- 자연 키: (PRICE_DATE, SOURCE_NAME, INDICATOR_CODE)
CREATE TABLE IF NOT EXISTS SOYBEAN_OIL.RAW.GEOPOLITICAL_INDICES (
    PRICE_DATE      DATE           NOT NULL,
    SOURCE_NAME     VARCHAR(100)   NOT NULL,
    INDICATOR_CODE  VARCHAR(50)    NOT NULL,
    VALUE           FLOAT          NOT NULL,
    UNIT            VARCHAR(50),
    NOTE            VARCHAR(200),
    INGESTED_AT     TIMESTAMP_NTZ  NOT NULL,
    _LOADED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_GPR PRIMARY KEY (PRICE_DATE, SOURCE_NAME, INDICATOR_CODE)
);

-- ── 접근 권한 (서비스 계정용 — SNOWFLAKE_USER 환경변수에 해당하는 사용자) ──
-- GRANT USAGE ON DATABASE SOYBEAN_OIL TO ROLE NEXUS_PIPELINE_ROLE;
-- GRANT USAGE ON SCHEMA SOYBEAN_OIL.RAW TO ROLE NEXUS_PIPELINE_ROLE;
-- GRANT INSERT, UPDATE, SELECT ON ALL TABLES IN SCHEMA SOYBEAN_OIL.RAW TO ROLE NEXUS_PIPELINE_ROLE;
